apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuboard.fullname" . }}
  labels:
    {{- include "kuboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "kuboard.selectorLabels" . | nindent 4 }}
    k8s.kuboard.cn/layer: monitor
    k8s.kuboard.cn/name: kuboard
