---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kuboard
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: kuboard
  chart:
    git: git@github.com:VarroReve/gitops
    path: charts/kuboard
    ref: master
