---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kuboard
  namespace: monitor
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:latest
spec:
  releaseName: kuboard
  chart:
    git: git@github.com:VarroReve/gitops
    path: charts/kuboard
    ref: master
  values:
    clusterRoleBinding:
      namespace: monitor