---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kuboard
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: ingress-nginx
  chart:
    git: git@github.com:VarroReve/gitops
    path: charts/ingress-nginx
    ref: master