---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kuboard
  namespace: monitor
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: ingress-nginx
  chart:
    git: git@github.com:VarroReve/gitops
    path: charts/ingress-nginx
    ref: master