---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: drone
  namespace: devops
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:~1.9
spec:
  releaseName: drone
  chart:
    repository: https://charts.drone.io
    name: drone
    version: 0.1.7
  values:
    env:
      DRONE_SERVER_HOST: drone.fmootech.cn
      DRONE_SERVER_PROTO: https
      DRONE_GITHUB_CLIENT_ID: 6e27d9e99b28d7ec9086
      DRONE_GITHUB_CLIENT_SECRET: 8c19b0b0e39df2f4afca7f4b207bc96afe36d7b3
      DRONE_RPC_SECRET: 8d7ec90e2c27d9e9
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: drone.fmootech.cn
          paths:
            - "/"
    tls:
      - secretName: drone-tls
        hosts:
          - drone.fmootech.cn