---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: drone-runner-kube
  namespace: devops
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: drone-runner-kube
  chart:
    repository: https://charts.drone.io
    name: drone-runner-kube
    version: 0.1.4
  values:
    env:
      DRONE_RPC_SECRET: 8d7ec90e2c27d9e9
      DRONE_NAMESPACE_DEFAULT: devops
    rbac:
      buildNamespaces:
        - devops