---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: blog
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1
spec:
  releaseName: blog
  chart:
    git: git@github.com:VarroReve/gitops
    path: charts/blog
    ref: master
  values:
    image:
      tag: 1.0.0
    ingress:
      hosts:
        - host: blog-prod.fmootech.cn
          paths: ["/"]
      tls:
        - secretName: blog-prod-tls
          hosts:
            - blog-prod.fmootech.cn