{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "blog.serviceAccountName" . }}
  labels:
{{ include "blog.labels" . | indent 4 }}
{{- end -}}
