---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: blog
  namespace: staging
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:staging-*
spec:
  releaseName: blog
  chart:
    git: git@github.com:VarroReve/gitops
    path: charts/blog
    ref: master
  values:
    image:
      repository: sakyavarro/blog
      tag: staging-d440a8a5
    ingress:
      hosts:
        - host: blog-staging.fmootech.cn
          paths: ["/"]
      tls:
        - secretName: blog-staging-tls
          hosts:
            - blog-staging.fmootech.cn