---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: blog
  namespace: varro
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:prod-*
spec:
  releaseName: blog
  chart:
    git: git@github.com:VarroReve/gitops
    path: charts/blog
    ref: master
  values:
    image:
      tag: 1.0.0
    ingress:
      hosts:
        - host: www.varroreve.com
          paths: ["/"]
      tls:
        - secretName: blog-varro-tls
          hosts:
            - www.varroreve.com